# Generated by Django 5.0.3 on 2025-11-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标类名（Font Awesome）')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '美食分类',
                'verbose_name_plural': '美食分类',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='美食名称')),
                ('english_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('description', models.TextField(verbose_name='美食介绍')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='主要食材')),
                ('cooking_method', models.TextField(blank=True, null=True, verbose_name='制作方法')),
                ('cultural_background', models.TextField(blank=True, null=True, verbose_name='文化背景')),
                ('cover_image', models.ImageField(upload_to='food_covers/', verbose_name='封面图')),
                ('price_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='价格区间')),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平均价格')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_traditional', models.BooleanField(default=False, verbose_name='是否传统美食')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='评分')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签（用逗号分隔）')),
                ('recommended_restaurants', models.TextField(blank=True, null=True, verbose_name='推荐餐厅（用换行分隔）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='foods.foodcategory', verbose_name='美食分类')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'ordering': ['display_order', '-is_hot', '-is_recommended', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/', verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='foods.food', verbose_name='所属美食')),
            ],
            options={
                'verbose_name': '美食图片',
                'verbose_name_plural': '美食图片',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category', '-is_hot', '-rating'], name='foods_food_categor_f25d89_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['-created_at'], name='foods_food_created_f22186_idx'),
        ),
    ]
