# Generated by Django 5.0.3 on 2025-11-27 00:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenic', '0002_alter_scenicspot_options_scenicspot_best_season_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='打卡时间')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='checkin_photos/', verbose_name='主照片')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='打卡纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='打卡经度')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='打卡备注')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scenic_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='scenic.scenicspot', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckInPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='checkin_photos/', verbose_name='照片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkins.checkin', verbose_name='打卡记录')),
            ],
            options={
                'verbose_name': '打卡照片',
                'verbose_name_plural': '打卡照片',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', '-checkin_time'], name='checkins_ch_user_id_018320_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['scenic_spot', '-checkin_time'], name='checkins_ch_scenic__3b0346_idx'),
        ),
    ]
