# Generated by Django 5.0.3 on 2025-12-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='check_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='入住日期'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='check_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='退房日期'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='item_type',
            field=models.CharField(choices=[('scenic', '景点门票'), ('route', '路线报名'), ('hotel', '酒店预订')], max_length=10, verbose_name='项目类型'),
        ),
    ]
