# Generated by Django 5.0.3 on 2025-11-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('abstract', models.CharField(max_length=255, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('cover_image', models.ImageField(upload_to='news_covers/', verbose_name='封面图')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
            ],
            options={
                'verbose_name': '旅游资讯',
                'verbose_name_plural': '旅游资讯',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '资讯分类',
                'verbose_name_plural': '资讯分类',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '资讯评论',
                'verbose_name_plural': '资讯评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
