# Generated by Django 5.0.3 on 2025-11-10 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('brief', models.CharField(max_length=255, verbose_name='简介')),
                ('description', models.TextField(verbose_name='详情介绍')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hotel_covers/', verbose_name='封面图')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='评分')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序（数字越小越靠前）')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'ordering': ['display_order', '-is_recommended', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房型名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('capacity', models.PositiveIntegerField(verbose_name='容纳人数')),
                ('description', models.TextField(verbose_name='房间描述')),
                ('remaining_count', models.PositiveIntegerField(default=0, verbose_name='剩余数量')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可预订')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='room_covers/', verbose_name='房间图片')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='所属酒店')),
            ],
            options={
                'verbose_name': '房间类型',
                'verbose_name_plural': '房间类型',
                'ordering': ['hotel', 'price', '-created_at'],
            },
        ),
    ]
