# Generated by Django 5.0.3 on 2025-12-18 00:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图片描述')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序（数字越小越靠前）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='所属酒店')),
            ],
            options={
                'verbose_name': '酒店图片',
                'verbose_name_plural': '酒店图片',
                'ordering': ['hotel', 'display_order', '-created_at'],
            },
        ),
    ]
