# Generated by Django 5.0.3 on 2025-11-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '路线分类',
                'verbose_name_plural': '路线分类',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='路线名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='天数')),
                ('group_size', models.PositiveIntegerField(default=10, verbose_name='成团人数')),
                ('deadline', models.DateField(verbose_name='报名截止时间')),
                ('cover_image', models.ImageField(upload_to='route_covers/', verbose_name='封面图')),
                ('itinerary_summary', models.TextField(verbose_name='行程概览')),
                ('cost_include', models.TextField(verbose_name='费用包含')),
                ('cost_exclude', models.TextField(verbose_name='费用不含')),
                ('notes', models.TextField(verbose_name='预订须知')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.routecategory', verbose_name='路线分类')),
            ],
            options={
                'verbose_name': '旅游路线',
                'verbose_name_plural': '旅游路线',
            },
        ),
        migrations.CreateModel(
            name='RouteItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='第几天')),
                ('title', models.CharField(max_length=200, verbose_name='当日标题')),
                ('description', models.TextField(verbose_name='行程描述 (含景点、餐饮、住宿)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='routes.route', verbose_name='所属路线')),
            ],
            options={
                'verbose_name': '每日行程',
                'verbose_name_plural': '每日行程',
                'ordering': ['day_number'],
            },
        ),
    ]
