# Generated by Django 5.0.3 on 2025-11-10 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['display_order', '-is_hot', '-rating', '-created_at'], 'verbose_name': '旅游路线', 'verbose_name_plural': '旅游路线'},
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_city',
            field=models.CharField(default='保定', max_length=50, verbose_name='出发城市'),
        ),
        migrations.AddField(
            model_name='route',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='显示顺序（数字越小越靠前）'),
        ),
        migrations.AddField(
            model_name='route',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='集合地点'),
        ),
        migrations.AddField(
            model_name='route',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='路线评分'),
        ),
        migrations.AddField(
            model_name='route',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='销售数量'),
        ),
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='特色标签（用逗号分隔）'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='route',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
