# Generated by Django 5.0.3 on 2025-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_options_route_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='route_covers/', verbose_name='封面图'),
        ),
    ]
