# Generated by Django 5.0.3 on 2025-11-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '景点分类',
                'verbose_name_plural': '景点分类',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='门票价格')),
                ('open_time', models.CharField(max_length=100, verbose_name='开放时间')),
                ('description', models.TextField(verbose_name='详细介绍')),
                ('cover_image', models.ImageField(upload_to='scenic_covers/', verbose_name='封面图')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='评分')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenic.sceniccategory', verbose_name='景点分类')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
        migrations.CreateModel(
            name='ScenicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scenic_images/', verbose_name='图片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scenic.scenicspot', verbose_name='所属景点')),
            ],
            options={
                'verbose_name': '景点图片',
                'verbose_name_plural': '景点图片',
                'ordering': ['order'],
            },
        ),
    ]
