# Generated by Django 5.0.3 on 2025-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenicspot',
            options={'ordering': ['display_order', '-is_hot', '-rating', '-created_at'], 'verbose_name': '景点', 'verbose_name_plural': '景点'},
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='best_season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='最佳游览季节'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='显示顺序（数字越小越靠前）'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标签（用逗号分隔）'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='traffic_info',
            field=models.TextField(blank=True, null=True, verbose_name='交通信息'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='visit_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建议游览时长'),
        ),
    ]
