# Generated by Django 5.0.3 on 2025-11-10 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('target_type', models.CharField(choices=[('scenic', '景点'), ('route', '路线'), ('hotel', '酒店'), ('news', '资讯')], max_length=20, verbose_name='关联对象类型')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='评分（1-5分）')),
                ('images', models.TextField(blank=True, null=True, verbose_name='评论图片（多个图片路径用逗号分隔）')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='comments_co_target__7045a1_idx'), models.Index(fields=['user', 'created_at'], name='comments_co_user_id_e44996_idx')],
            },
        ),
    ]
