# Generated by Django 5.0.3 on 2025-12-17 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('route', '路线规划'), ('transport', '交通规划'), ('strategy', '旅游策略'), ('general', '综合规划')], default='general', max_length=20, verbose_name='查询类型')),
                ('scenic_spots', models.TextField(verbose_name='景点列表（JSON格式）')),
                ('user_input', models.TextField(verbose_name='用户输入内容')),
                ('route_plan', models.TextField(blank=True, null=True, verbose_name='路线规划')),
                ('transport_plan', models.TextField(blank=True, null=True, verbose_name='交通规划')),
                ('strategy_plan', models.TextField(blank=True, null=True, verbose_name='旅游策略')),
                ('full_response', models.TextField(blank=True, null=True, verbose_name='完整AI响应')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户（未登录用户为null）')),
            ],
            options={
                'verbose_name': 'AI查询记录',
                'verbose_name_plural': 'AI查询记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
